version: '3'
services:
  web: 
    container_name: react-frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "2000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests: 
    container_name: react-frontend-test

    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm" , "run", "test"]    