name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t vikasjain1980/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true vikasjain1980/docker-react npm test
